export const dummyRestaurants = [
  {
    id: "dummy-1",
    name: "Spicy Treats",
    image: "/biryani_gemini.png",
    rating: "4.5",
    latitude: "20.2961",
    longitude: "85.8245",
    isOpen: true,
    deliveryRange: "10000",
    cuisine: "Indian",
    time: "25 min",
    minOrder: 150,
    veg: true,
    offer: "10% OFF",
  },
  {
    id: "dummy-2",
    name: "Burger Queen",
    image: "/burger_gemini.png",
    rating: "4.2",
    latitude: "20.2961",
    longitude: "85.8245",
    isOpen: true,
    deliveryRange: "10000",
    cuisine: "Fast Food",
    time: "30 min",
    minOrder: 100,
    veg: false,
  },
  {
    id: "dummy-3",
    name: "The Dosa Place",
    image: "/dosa.png",
    rating: "4.7",
    latitude: "20.2961",
    longitude: "85.8245",
    isOpen: true,
    deliveryRange: "10000",
    cuisine: "South Indian",
    time: "20 min",
    minOrder: 120,
    veg: true,
    offer: "Free Delivery",
  },
  {
    id: "dummy-4",
    name: "Noodle Hub",
    image: "/chowmin_gemini.png",
    rating: "4.0",
    latitude: "20.2961",
    longitude: "85.8245",
    isOpen: true,
    deliveryRange: "10000",
    cuisine: "Chinese",
    time: "35 min",
    minOrder: 200,
    veg: false,
  },
  {
    id: "dummy-5",
    name: "Momo Magic",
    image: "/momo_gemini.png",
    rating: "4.3",
    latitude: "20.2961",
    longitude: "85.8245",
    isOpen: true,
    deliveryRange: "10000",
    cuisine: "Tibetan",
    time: "15 min",
    minOrder: 80,
    veg: false,
  },
  {
    id: "dummy-6",
    name: "Pizza Paradise",
    image: "/pizza_gemini.png",
    rating: "4.6",
    latitude: "20.2961",
    longitude: "85.8245",
    isOpen: true,
    deliveryRange: "10000",
    cuisine: "Italian",
    time: "40 min",
    minOrder: 250,
    veg: true,
    offer: "Buy 1 Get 1 Free",
  },
  {
    id: "dummy-7",
    name: "Roll Express",
    image: "/roll.png",
    rating: "4.1",
    latitude: "20.2961",
    longitude: "85.8245",
    isOpen: true,
    deliveryRange: "10000",
    cuisine: "Indian Fast Food",
    time: "20 min",
    minOrder: 100,
    veg: false,
  },
  {
    id: "dummy-8",
    name: "Kebab Korner",
    image: "/chicken_kabab.png",
    rating: "4.8",
    latitude: "20.2961",
    longitude: "85.8245",
    isOpen: true,
    deliveryRange: "10000",
    cuisine: "Mughlai",
    time: "45 min",
    minOrder: 300,
    veg: false,
    offer: "15% OFF",
  },
  {
    id: "dummy-9",
    name: "Pasta Punto",
    image: "/pasta.png",
    rating: "4.2",
    latitude: "20.2961",
    longitude: "85.8245",
    isOpen: true,
    deliveryRange: "10000",
    cuisine: "Italian",
    time: "30 min",
    minOrder: 200,
    veg: true,
  },
  {
    id: "dummy-10",
    name: "Sandwich Station",
    image: "/sandwich.png",
    rating: "4.4",
    latitude: "20.2961",
    longitude: "85.8245",
    isOpen: true,
    deliveryRange: "10000",
    cuisine: "Fast Food",
    time: "15 min",
    minOrder: 150,
    veg: true,
  },
  {
    id: "dummy-11",
    name: "Pakoda Point",
    image: "/chicken_pakoda.png",
    rating: "4.3",
    latitude: "20.2961",
    longitude: "85.8245",
    isOpen: true,
    deliveryRange: "10000",
    cuisine: "Indian Snacks",
    time: "25 min",
    minOrder: 100,
    veg: false,
  },
  {
    id: "dummy-12",
    name: "Vada Junction",
    image: "/vada.png",
    rating: "4.5",
    latitude: "20.2961",
    longitude: "85.8245",
    isOpen: true,
    deliveryRange: "10000",
    cuisine: "South Indian",
    time: "20 min",
    minOrder: 80,
    veg: true,
    offer: "Free Delivery",
  },
  {
    id: "dummy-13",
    name: "Manchurian Master",
    image: "/manchurian.png",
    rating: "4.1",
    latitude: "20.2961",
    longitude: "85.8245",
    isOpen: true,
    deliveryRange: "10000",
    cuisine: "Chinese",
    time: "30 min",
    minOrder: 150,
    veg: true,
  },
  {
    id: "dummy-14",
    name: "Sweet Bakery",
    image: "/bakery_cake_and_hotdog.png",
    rating: "4.6",
    latitude: "20.2961",
    longitude: "85.8245",
    isOpen: true,
    deliveryRange: "10000",
    cuisine: "Desserts",
    time: "40 min",
    minOrder: 200,
    veg: true,
  },
  {
    id: "dummy-15",
    name: "Chill Drinks",
    image: "/drinks_blue_mojito.png",
    rating: "4.7",
    latitude: "20.2961",
    longitude: "85.8245",
    isOpen: true,
    deliveryRange: "10000",
    cuisine: "Beverages",
    time: "15 min",
    minOrder: 100,
    veg: true,
    offer: "20% OFF",
  },
  {
    id: "dummy-16",
    name: "Punjabi Chole",
    image: "/chole_bhature.png",
    rating: "4.4",
    latitude: "20.2961",
    longitude: "85.8245",
    isOpen: true,
    deliveryRange: "10000",
    cuisine: "North Indian",
    time: "35 min",
    minOrder: 180,
    veg: true,
  },
  {
    id: "dummy-17",
    name: "Samosa Story",
    image: "/samosa_gemini.png",
    rating: "4.2",
    latitude: "20.2961",
    longitude: "85.8245",
    isOpen: true,
    deliveryRange: "10000",
    cuisine: "Indian Snacks",
    time: "20 min",
    minOrder: 50,
    veg: true,
  },
  {
    id: "dummy-18",
    name: "Biryani Brothers",
    image: "/biryani_gemini.png",
    rating: "4.8",
    latitude: "20.2961",
    longitude: "85.8245",
    isOpen: true,
    deliveryRange: "10000",
    cuisine: "Indian",
    time: "45 min",
    minOrder: 300,
    veg: false,
    offer: "Super Deal",
  },
  {
    id: "dummy-19",
    name: "Crispy Bites",
    image: "/others_gemini.png",
    rating: "4.0",
    latitude: "20.2961",
    longitude: "85.8245",
    isOpen: true,
    deliveryRange: "10000",
    cuisine: "Fast Food",
    time: "25 min",
    minOrder: 120,
    veg: true,
  },
  {
    id: "dummy-20",
    name: "Golden Wok",
    image: "/chowmin_gemini.png",
    rating: "4.3",
    latitude: "20.2961",
    longitude: "85.8245",
    isOpen: true,
    deliveryRange: "10000",
    cuisine: "Chinese",
    time: "30 min",
    minOrder: 220,
    veg: false,
  },
  {
    id: "dummy-21",
    name: "Pizza Planet",
    image: "/pizza_gemini.png",
    rating: "4.1",
    latitude: "20.2961",
    longitude: "85.8245",
    isOpen: true,
    deliveryRange: "10000",
    cuisine: "Italian",
    time: "35 min",
    minOrder: 250,
    veg: false,
    offer: "10% OFF",
  },
  {
    id: "dummy-22",
    name: "Dosa Diner",
    image: "/dosa.png",
    rating: "4.6",
    latitude: "20.2961",
    longitude: "85.8245",
    isOpen: true,
    deliveryRange: "10000",
    cuisine: "South Indian",
    time: "25 min",
    minOrder: 150,
    veg: true,
  },
  {
    id: "dummy-23",
    name: "The Momo Co.",
    image: "/momo_gemini.png",
    rating: "4.4",
    latitude: "20.2961",
    longitude: "85.8245",
    isOpen: true,
    deliveryRange: "10000",
    cuisine: "Tibetan",
    time: "20 min",
    minOrder: 100,
    veg: false,
  },
  {
    id: "dummy-24",
    name: "Rolls Royce",
    image: "/roll.png",
    rating: "4.7",
    latitude: "20.2961",
    longitude: "85.8245",
    isOpen: true,
    deliveryRange: "10000",
    cuisine: "Indian Fast Food",
    time: "20 min",
    minOrder: 180,
    veg: false,
    offer: "Free Beverage",
  },
  {
    id: "dummy-25",
    name: "Grill & Chill",
    image: "/chicken_kabab.png",
    rating: "4.5",
    latitude: "20.2961",
    longitude: "85.8245",
    isOpen: true,
    deliveryRange: "10000",
    cuisine: "Mughlai",
    time: "40 min",
    minOrder: 350,
    veg: false,
  },
  {
    id: "dummy-26",
    name: "Pasta Perfetto",
    image: "/pasta.png",
    rating: "4.3",
    latitude: "20.2961",
    longitude: "85.8245",
    isOpen: true,
    deliveryRange: "10000",
    cuisine: "Italian",
    time: "35 min",
    minOrder: 220,
    veg: true,
  },
  {
    id: "dummy-27",
    name: "Burger Boss",
    image: "/burger_gemini.png",
    rating: "4.2",
    latitude: "20.2961",
    longitude: "85.8245",
    isOpen: true,
    deliveryRange: "10000",
    cuisine: "Fast Food",
    time: "30 min",
    minOrder: 150,
    veg: false,
  },
  {
    id: "dummy-28",
    name: "Snack Time",
    image: "/sandwich.png",
    rating: "4.0",
    latitude: "20.2961",
    longitude: "85.8245",
    isOpen: true,
    deliveryRange: "10000",
    cuisine: "Fast Food",
    time: "15 min",
    minOrder: 100,
    veg: true,
  },
  {
    id: "dummy-29",
    name: "Sweet Tooth",
    image: "/bakery_cake_and_hotdog.png",
    rating: "4.8",
    latitude: "20.2961",
    longitude: "85.8245",
    isOpen: true,
    deliveryRange: "10000",
    cuisine: "Desserts",
    time: "45 min",
    minOrder: 250,
    veg: true,
    offer: "15% OFF",
  },
  {
    id: "dummy-30",
    name: "Thirst Quencher",
    image: "/drinks_blue_mojito.png",
    rating: "4.6",
    latitude: "20.2961",
    longitude: "85.8245",
    isOpen: true,
    deliveryRange: "10000",
    cuisine: "Beverages",
    time: "10 min",
    minOrder: 80,
    veg: true,
  }
];
